DROP TABLE IF EXISTS `Pokemon`;
CREATE TABLE Pokemon (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    pokemon_name VARCHAR(100),
    pokemon_ability VARCHAR(100),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `Bible`;
CREATE TABLE Bible (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    bible_verse VARCHAR(200),
    pokemon_id INT,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (pokemon_id)
        REFERENCES Pokemon (id)
);
